 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/student_members", type: :request do
  
  # StudentMember. As you add validations to StudentMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StudentMember.create! valid_attributes
      get student_members_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      student_member = StudentMember.create! valid_attributes
      get student_member_url(student_member)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_student_member_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      student_member = StudentMember.create! valid_attributes
      get edit_student_member_url(student_member)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StudentMember" do
        expect {
          post student_members_url, params: { student_member: valid_attributes }
        }.to change(StudentMember, :count).by(1)
      end

      it "redirects to the created student_member" do
        post student_members_url, params: { student_member: valid_attributes }
        expect(response).to redirect_to(student_member_url(StudentMember.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StudentMember" do
        expect {
          post student_members_url, params: { student_member: invalid_attributes }
        }.to change(StudentMember, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post student_members_url, params: { student_member: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested student_member" do
        student_member = StudentMember.create! valid_attributes
        patch student_member_url(student_member), params: { student_member: new_attributes }
        student_member.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the student_member" do
        student_member = StudentMember.create! valid_attributes
        patch student_member_url(student_member), params: { student_member: new_attributes }
        student_member.reload
        expect(response).to redirect_to(student_member_url(student_member))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        student_member = StudentMember.create! valid_attributes
        patch student_member_url(student_member), params: { student_member: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested student_member" do
      student_member = StudentMember.create! valid_attributes
      expect {
        delete student_member_url(student_member)
      }.to change(StudentMember, :count).by(-1)
    end

    it "redirects to the student_members list" do
      student_member = StudentMember.create! valid_attributes
      delete student_member_url(student_member)
      expect(response).to redirect_to(student_members_url)
    end
  end
end
