 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/officer_pics", type: :request do
  
  # OfficerPic. As you add validations to OfficerPic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OfficerPic.create! valid_attributes
      get officer_pics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      officer_pic = OfficerPic.create! valid_attributes
      get officer_pic_url(officer_pic)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_officer_pic_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      officer_pic = OfficerPic.create! valid_attributes
      get edit_officer_pic_url(officer_pic)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OfficerPic" do
        expect {
          post officer_pics_url, params: { officer_pic: valid_attributes }
        }.to change(OfficerPic, :count).by(1)
      end

      it "redirects to the created officer_pic" do
        post officer_pics_url, params: { officer_pic: valid_attributes }
        expect(response).to redirect_to(officer_pic_url(OfficerPic.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OfficerPic" do
        expect {
          post officer_pics_url, params: { officer_pic: invalid_attributes }
        }.to change(OfficerPic, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post officer_pics_url, params: { officer_pic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested officer_pic" do
        officer_pic = OfficerPic.create! valid_attributes
        patch officer_pic_url(officer_pic), params: { officer_pic: new_attributes }
        officer_pic.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the officer_pic" do
        officer_pic = OfficerPic.create! valid_attributes
        patch officer_pic_url(officer_pic), params: { officer_pic: new_attributes }
        officer_pic.reload
        expect(response).to redirect_to(officer_pic_url(officer_pic))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        officer_pic = OfficerPic.create! valid_attributes
        patch officer_pic_url(officer_pic), params: { officer_pic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested officer_pic" do
      officer_pic = OfficerPic.create! valid_attributes
      expect {
        delete officer_pic_url(officer_pic)
      }.to change(OfficerPic, :count).by(-1)
    end

    it "redirects to the officer_pics list" do
      officer_pic = OfficerPic.create! valid_attributes
      delete officer_pic_url(officer_pic)
      expect(response).to redirect_to(officer_pics_url)
    end
  end
end
