# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe('/business_professionals', type: :request) do
  # BusinessProfessional. As you add validations to BusinessProfessional, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BusinessProfessional.create!(valid_attributes)
      get business_professionals_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      business_professional = BusinessProfessional.create!(valid_attributes)
      get business_professional_url(business_professional)
      expect(response).to(be_successful)
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_business_professional_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      business_professional = BusinessProfessional.create!(valid_attributes)
      get edit_business_professional_url(business_professional)
      expect(response).to(be_successful)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BusinessProfessional' do
        expect do
          post(business_professionals_url, params: { business_professional: valid_attributes })
        end.to(change(BusinessProfessional, :count).by(1))
      end

      it 'redirects to the created business_professional' do
        post business_professionals_url, params: { business_professional: valid_attributes }
        expect(response).to(redirect_to(business_professional_url(BusinessProfessional.last)))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BusinessProfessional' do
        expect do
          post(business_professionals_url, params: { business_professional: invalid_attributes })
        end.to(change(BusinessProfessional, :count).by(0))
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post business_professionals_url, params: { business_professional: invalid_attributes }
        expect(response).to(be_successful)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested business_professional' do
        business_professional = BusinessProfessional.create!(valid_attributes)
        patch business_professional_url(business_professional), params: { business_professional: new_attributes }
        business_professional.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the business_professional' do
        business_professional = BusinessProfessional.create!(valid_attributes)
        patch business_professional_url(business_professional), params: { business_professional: new_attributes }
        business_professional.reload
        expect(response).to(redirect_to(business_professional_url(business_professional)))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        business_professional = BusinessProfessional.create!(valid_attributes)
        patch business_professional_url(business_professional), params: { business_professional: invalid_attributes }
        expect(response).to(be_successful)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested business_professional' do
      business_professional = BusinessProfessional.create!(valid_attributes)
      expect do
        delete(business_professional_url(business_professional))
      end.to(change(BusinessProfessional, :count).by(-1))
    end

    it 'redirects to the business_professionals list' do
      business_professional = BusinessProfessional.create!(valid_attributes)
      delete business_professional_url(business_professional)
      expect(response).to(redirect_to(business_professionals_url))
    end
  end
end
