# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe('/event_business_professionals', type: :request) do
  # EventBusinessProfessional. As you add validations to EventBusinessProfessional, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      EventBusinessProfessional.create!(valid_attributes)
      get event_business_professionals_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      event_business_professional = EventBusinessProfessional.create!(valid_attributes)
      get event_business_professional_url(event_business_professional)
      expect(response).to(be_successful)
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_event_business_professional_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      event_business_professional = EventBusinessProfessional.create!(valid_attributes)
      get edit_event_business_professional_url(event_business_professional)
      expect(response).to(be_successful)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new EventBusinessProfessional' do
        expect do
          post(event_business_professionals_url, params: { event_business_professional: valid_attributes })
        end.to(change(EventBusinessProfessional, :count).by(1))
      end

      it 'redirects to the created event_business_professional' do
        post event_business_professionals_url, params: { event_business_professional: valid_attributes }
        expect(response).to(redirect_to(event_business_professional_url(EventBusinessProfessional.last)))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new EventBusinessProfessional' do
        expect do
          post(event_business_professionals_url, params: { event_business_professional: invalid_attributes })
        end.to(change(EventBusinessProfessional, :count).by(0))
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post event_business_professionals_url, params: { event_business_professional: invalid_attributes }
        expect(response).to(be_successful)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested event_business_professional' do
        event_business_professional = EventBusinessProfessional.create!(valid_attributes)
        patch event_business_professional_url(event_business_professional), params: { event_business_professional: new_attributes }
        event_business_professional.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the event_business_professional' do
        event_business_professional = EventBusinessProfessional.create!(valid_attributes)
        patch event_business_professional_url(event_business_professional), params: { event_business_professional: new_attributes }
        event_business_professional.reload
        expect(response).to(redirect_to(event_business_professional_url(event_business_professional)))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        event_business_professional = EventBusinessProfessional.create!(valid_attributes)
        patch event_business_professional_url(event_business_professional), params: { event_business_professional: invalid_attributes }
        expect(response).to(be_successful)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested event_business_professional' do
      event_business_professional = EventBusinessProfessional.create!(valid_attributes)
      expect do
        delete(event_business_professional_url(event_business_professional))
      end.to(change(EventBusinessProfessional, :count).by(-1))
    end

    it 'redirects to the event_business_professionals list' do
      event_business_professional = EventBusinessProfessional.create!(valid_attributes)
      delete event_business_professional_url(event_business_professional)
      expect(response).to(redirect_to(event_business_professionals_url))
    end
  end
end
